In [1]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

2.0.0
We have a GPU!


In [2]:
#tensor multiplication

float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
int32_tensor = torch.tensor([3, 4, 5], dtype=torch.long)
multiplied_tensor = float16_tensor * int32_tensor
print(multiplied_tensor)
print(multiplied_tensor.dtype)
print(multiplied_tensor.device)

tensor([ 9., 24., 45.])
torch.float32
cpu


In [3]:
#tensor division

int32_tensor_2 = torch.tensor([5,6,7])
int32_tensor_3 = torch.tensor([1,2,3])
division_tensor = int32_tensor_2 / int32_tensor_3
print(division_tensor)
print(division_tensor.dtype)

tensor([5.0000, 3.0000, 2.3333])
torch.float32


In [5]:
#tensor type conversion

old_tensor = torch.tensor([1.1, 2.2, 3.3], dtype=torch.float32)
print(old_tensor.dtype)
new_tensor = old_tensor.type(torch.float16)
print(new_tensor.dtype)
print(new_tensor)

torch.float32
torch.float16
tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16)


In [6]:
#tensor manipulation (built-in): vector-scalar multiplication

print(new_tensor)
#use * in python unless specified for simplification (simple operation only)
print(new_tensor*10)
print(torch.mul(new_tensor, 10))

tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16)
tensor([11., 22., 33.], dtype=torch.float16)
tensor([11., 22., 33.], dtype=torch.float16)


In [8]:
%%time

#time for multiplication

#matrix multiplcation: dot product
print(old_tensor)
print(old_tensor*old_tensor)
print(torch.matmul(old_tensor, old_tensor))
matrix22_1 = torch.tensor([[[1, 2], [3, 4]]])
matrix22_2 = torch.tensor([[[5, 6], [7, 8]]])
print(torch.matmul(matrix22_1, matrix22_2))

tensor([1.1000, 2.2000, 3.3000])
tensor([ 1.2100,  4.8400, 10.8900])
tensor(16.9400)
tensor([[[19, 22],
         [43, 50]]])
CPU times: total: 0 ns
Wall time: 4 ms


In [9]:
#errors in matrix multiplication
matrix33_1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(torch.matmul(matrix22_1, matrix33_1))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 3x3)