In [1]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

2.0.0
We have a GPU!


In [3]:
#matrix transpose

matrix22_1 = torch.tensor([[[1, 2], [3, 4]]])
matrix23_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix23_1.T)
print(matrix23_1.shape)
print(matrix23_1.T.shape)
print(torch.matmul(matrix22_1, matrix23_1))

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[[ 9, 12, 15],
         [19, 26, 33]]])


In [4]:
#tensor attributes

print(matrix23_1.min())
print(matrix23_1.max())
print(matrix23_1.sum())
print(torch.mean(matrix23_1.type(torch.float32)))
#no change in datatype can result in error
print(torch.mean(matrix23_1()))

tensor(1)
tensor(6)
tensor(21)
tensor(3.5000)


TypeError: 'Tensor' object is not callable

In [6]:
#argmin/argmax: find the INDEX in the tensor that has the minimum/maximum value

print(matrix23_1.argmin())
print(matrix23_1.argmax())

tensor(0)
tensor(5)


In [7]:
#reshaping (reshape tensors to defined shape)
x = torch.arange(1., 10.)
print(x)
x_reshaped = x.reshape(3, 3) #can be reshaped to 1*9, 3*3 or 9*1 matrix
print(x_reshaped)

#view (return a view of an input tensor of certain shape but keep the same memory as original tensor)

z = x.view(1, 9)
z[:, 0] = 3
print(z, x) #z shares the same mmory as x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])


In [8]:
#stacking (combine mutltiple tensors on top of each other or side by side)

x_stacked  = torch.stack([x, x, x])
x_hstacked = torch.hstack([x, x, x])
x_vstacked = torch.vstack([x, x, x])
print(x_stacked)
print(x_stacked.shape)
print(x_hstacked)
print(x_hstacked.shape)
print(x_vstacked)
print(x_vstacked.shape)

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([3, 9])
tensor([3., 2., 3., 4., 5., 6., 7., 8., 9., 3., 2., 3., 4., 5., 6., 7., 8., 9.,
        3., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([27])
tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([3, 9])


In [9]:
#squeezing (remove all '1' dimensions from tensor) and unsqueezing (add a '1' dimension to a target tensor)

x_reshaped = x.reshape(1, 9)
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed)

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[3.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [13]:
#permute (return a view of input with dimensions permuted (swapped) in certain way)

#image tensor: height, width, color channels (RGB)
image_size_tensor = torch.rand(size=(224, 224, 3))
print(image_size_tensor) #height, width, colour
x_permuted = image_size_tensor.permute(2, 0, 1)
print(x_permuted)
print(image_size_tensor.size())
print(x_permuted.size())

tensor([[[0.1607, 0.7667, 0.5178],
         [0.1326, 0.5432, 0.6364],
         [0.9319, 0.6327, 0.0786],
         ...,
         [0.7123, 0.3931, 0.6472],
         [0.4296, 0.8524, 0.3174],
         [0.7614, 0.4917, 0.6192]],

        [[0.0974, 0.9017, 0.0955],
         [0.4971, 0.8983, 0.2200],
         [0.5274, 0.0284, 0.0601],
         ...,
         [0.5779, 0.5516, 0.6370],
         [0.0339, 0.5058, 0.5921],
         [0.2487, 0.4848, 0.6203]],

        [[0.6667, 0.3570, 0.9490],
         [0.6238, 0.6423, 0.9713],
         [0.9419, 0.6970, 0.9941],
         ...,
         [0.4371, 0.9418, 0.9686],
         [0.3538, 0.8086, 0.8804],
         [0.9209, 0.1960, 0.6236]],

        ...,

        [[0.0060, 0.7011, 0.0954],
         [0.5936, 0.2393, 0.1787],
         [0.1892, 0.1470, 0.9705],
         ...,
         [0.9372, 0.8320, 0.1540],
         [0.7428, 0.4183, 0.1888],
         [0.5857, 0.7787, 0.2976]],

        [[0.9045, 0.6649, 0.7446],
         [0.3856, 0.7133, 0.7929],
         [0.

In [12]:
#indexing

x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(x[0])
print(x[0, 1, 1])
print(x[:, :, 2])
print(x[:, 1, 0])
print(x[0, 1, :])
print(x[0, :, 2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(5)
tensor([[3, 6, 9]])
tensor([4])
tensor([4, 5, 6])
tensor([3, 6, 9])
