In [2]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

2.0.0
We have a GPU!


In [3]:
scalar = torch.tensor(4)
scalar.item()

4

In [4]:
#tensor
vector_set = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
simple_vector_1 = torch.tensor([1, 2, 3], dtype=torch.float32)
simple_vector_2 = torch.tensor([4.2, 5.6, 7.6])
multiplied_vector_3 = simple_vector_1 * simple_vector_2
print(vector_set.ndim)
print(vector_set.shape)
print(vector_set[0].size())
print(vector_set.device)
print(simple_vector_1.dtype)
print(multiplied_vector_3.dtype) #default int64, if floating number exists, float32
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, device=None, requires_grad=False)
print(float16_tensor.dtype)

3
torch.Size([2, 3, 3])
torch.Size([3, 3])
cpu
torch.float32
torch.float32
torch.float16


In [6]:
vector_set.shape

torch.Size([2, 3, 3])

In [7]:
#creating tensors
tensor_random = torch.rand(2, 3)
print(tensor_random)
#image tensor: height, width, color channels (RGB)
image_size_tensor = torch.rand(size=(224, 224, 3))

tensor([[0.6644, 0.2523, 0.0863],
        [0.6740, 0.0029, 0.9383]])


In [8]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(f"Shape of tensor: {x_data.shape}")
print(f"Datatype of tensor: {x_data.dtype}")
print(f"Device tensor is stored on: {x_data.device}")

tensor([[1, 2],
        [3, 4]])
Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [9]:
#zeros tensor
zero_tensor = torch.zeros(size=(2, 3))
#ones tensor
ones_tensor = torch.ones(size=(2, 3))
ones_tensor.dtype

torch.float32

In [10]:
#range and steps
range_tensor = torch.arange(1, 10)
range_tensor
step_tensor = torch.arange(start = 2, end = 11, step = 2)
step_tensor

tensor([ 2,  4,  6,  8, 10])

In [11]:
#tensor data type
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float16_tensor.dtype

torch.float32

In [12]:
#data type coersion and check shape
int32_tensor = torch.tensor([3, 4, 5], dtype=torch.long)
print(int32_tensor.size())
print(int32_tensor.shape)

torch.Size([3])
torch.Size([3])


In [13]:
multiplied_tensor = float16_tensor * int32_tensor
print(multiplied_tensor)
print(multiplied_tensor.dtype)
print(multiplied_tensor.device)

tensor([ 9., 24., 45.])
torch.float32
cpu


In [14]:
int32_tensor_2 = torch.tensor([5,6,7])
int32_tensor_3 = torch.tensor([1,2,3])
division_tensor = int32_tensor_2 / int32_tensor_3
print(division_tensor)
print(division_tensor.dtype)

tensor([5.0000, 3.0000, 2.3333])
torch.float32


In [15]:
#tensor type conversion
old_tensor = torch.tensor([1.1, 2.2, 3.3], dtype=torch.float32)
print(old_tensor.dtype)
new_tensor = old_tensor.type(torch.float16)
print(new_tensor.dtype)
print(new_tensor)

torch.float32
torch.float16
tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16)


In [16]:
#tensor manipulation (built-in): vector-scalar multiplication
print(new_tensor)
#use * in python unless specified for simplification (simple operation only)
print(new_tensor*10)
print(torch.mul(new_tensor, 10))

tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16)
tensor([11., 22., 33.], dtype=torch.float16)
tensor([11., 22., 33.], dtype=torch.float16)


In [17]:
%%time
#matrix multiplcation: dot product
print(old_tensor)
print(old_tensor*old_tensor)
print(torch.matmul(old_tensor, old_tensor))
matrix22_1 = torch.tensor([[[1, 2], [3, 4]]])
matrix22_2 = torch.tensor([[[5, 6], [7, 8]]])
print(torch.matmul(matrix22_1, matrix22_2))

tensor([1.1000, 2.2000, 3.3000])
tensor([ 1.2100,  4.8400, 10.8900])
tensor(16.9400)
tensor([[[19, 22],
         [43, 50]]])
CPU times: total: 0 ns
Wall time: 1.97 ms


In [18]:
#errors in matrix multiplication
matrix33_1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(torch.matmul(matrix22_1, matrix33_1))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 3x3)

In [21]:
#matrix transpose
matrix23_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix23_1.T)
print(matrix23_1.shape)
print(matrix23_1.T.shape)
print(torch.matmul(matrix22_1, matrix23_1))

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[[ 9, 12, 15],
         [19, 26, 33]]])


In [36]:
#tensor attributes
print(matrix23_1.min())
print(matrix23_1.max())
print(matrix23_1.sum())
print(torch.mean(matrix23_1.type(torch.float32)))
#no change in datatype can result in error
print(torch.mean(matrix23_1()))

tensor(1)
tensor(6)
tensor(21)
tensor(3.5000)


TypeError: 'Tensor' object is not callable

In [38]:
#argmin/argmax: find the index in the tensor that has the minimum/maximum value
print(matrix23_1.argmin())
print(matrix23_1.argmax())

tensor(0)
tensor(5)


In [54]:
x = torch.arange(1., 10.)
print(x)
#reshaping (reshape tensors to defined shape), view (return a view of an input tensor of certain shape but keep the same memory as original tensor)
x_reshaped = x.reshape(3, 3) #can be reshaped to 1*9, 3*3 or 9*1 matrix
print(x_reshaped)
z = x.view(1, 9)
z[:, 0] = 3
print(z, x) #z shares the same mmory as x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])


In [58]:
#stacking (combine mutltiple tensors on top of each other or side by side)
x_stacked  = torch.stack([x, x, x])
x_hstacked = torch.hstack([x, x, x])
x_vstacked = torch.vstack([x, x, x])
print(x_stacked)
print(x_stacked.shape)
print(x_hstacked)
print(x_hstacked.shape)
print(x_vstacked)
print(x_vstacked.shape)

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([3, 9])
tensor([3., 2., 3., 4., 5., 6., 7., 8., 9., 3., 2., 3., 4., 5., 6., 7., 8., 9.,
        3., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([27])
tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([3, 9])


In [63]:
#squeezing (remove all '1' dimensions from tensor) and unsqueezing (add a '1' dimension to a target tensor)
x_reshaped = x.reshape(1, 9)
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed)

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[3.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [69]:
#permute (return a view of input with dimensions permuted (swapped) in certain way)
print(image_size_tensor) #height, width, colour
x_permuted = image_size_tensor.permute(2, 0, 1)
print(x_permuted)
print(image_size_tensor.size())
print(x_permuted.size())

tensor([[[0.2416, 0.0934, 0.9053],
         [0.5098, 0.4431, 0.8598],
         [0.1903, 0.0632, 0.7153],
         ...,
         [0.8239, 0.5739, 0.8050],
         [0.2270, 0.5444, 0.6461],
         [0.1357, 0.8988, 0.8580]],

        [[0.0722, 0.2897, 0.4688],
         [0.2544, 0.6159, 0.8463],
         [0.3489, 0.5832, 0.7665],
         ...,
         [0.1973, 0.3163, 0.1076],
         [0.0973, 0.9661, 0.4149],
         [0.6374, 0.8460, 0.4623]],

        [[0.1865, 0.0222, 0.8014],
         [0.3009, 0.3172, 0.0399],
         [0.7620, 0.7147, 0.5854],
         ...,
         [0.2592, 0.4385, 0.5496],
         [0.3808, 0.9676, 0.9981],
         [0.6808, 0.6183, 0.8669]],

        ...,

        [[0.6926, 0.9068, 0.1222],
         [0.4959, 0.6266, 0.4768],
         [0.1589, 0.4419, 0.4530],
         ...,
         [0.0818, 0.7308, 0.8948],
         [0.4867, 0.9127, 0.4676],
         [0.0917, 0.5930, 0.6689]],

        [[0.7684, 0.9492, 0.0095],
         [0.8020, 0.6667, 0.5986],
         [0.

In [82]:
#indexing
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(x[0])
print(x[0, 1, 1])
print(x[:, :, 2])
print(x[:, 1, 0])
print(x[0, 1, :])
print(x[0, :, 2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(5)
tensor([[3, 6, 9]])
tensor([4])
tensor([4, 5, 6])
tensor([3, 6, 9])


In [101]:
import numpy as np
#numpy to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
print(array)
print(tensor)
print(tensor.dtype)
array = array+1
print(array)
print(tensor)

#tensor to numpy
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()
print(tensor)
print(numpy_tensor)
tensor = tensor+1
print(tensor)
print(numpy_tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.])
torch.float32
[2. 3. 4. 5. 6. 7. 8.]
tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#reproducibility
