In [47]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

2.0.0
We have a GPU!


In [48]:
scalar = torch.tensor(4)
scalar.item()

4

In [49]:
#tensor
vector_set = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
simple_vector_1 = torch.tensor([1, 2, 3], dtype=torch.float32)
simple_vector_2 = torch.tensor([4.2, 5.6, 7.6])
multiplied_vector_3 = simple_vector_1 * simple_vector_2
print(vector_set.ndim)
print(vector_set.shape)
print(vector_set[0].size())
print(vector_set.device)
print(simple_vector_1.dtype)
print(multiplied_vector_3.dtype) #default int64, if floating number exists, float32
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, device=None, requires_grad=False)
print(float16_tensor.dtype)

3
torch.Size([2, 3, 3])
torch.Size([3, 3])
cpu
torch.float32
torch.float32
torch.float16


In [50]:
vector.shape

torch.Size([2, 3, 3])

In [51]:
#creating tensors
tensor_random = torch.rand(2, 3)
print(tensor_random)
#image tensor: height, width, color channels (RGB)
image_size_tensor = torch.rand(size=(224, 224, 3))

tensor([[0.5904, 0.6271, 0.5268],
        [0.4524, 0.1170, 0.8031]])


In [52]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(f"Shape of tensor: {x_data.shape}")
print(f"Datatype of tensor: {x_data.dtype}")
print(f"Device tensor is stored on: {x_data.device}")

tensor([[1, 2],
        [3, 4]])
Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [53]:
#zeros tensor
zero_tensor = torch.zeros(size=(2, 3))
#ones tensor
ones_tensor = torch.ones(size=(2, 3))
ones_tensor.dtype

torch.float32

In [54]:
#range and steps
range_tensor = torch.arange(1, 10)
range_tensor
step_tensor = torch.arange(start = 2, end = 11, step = 2)
step_tensor

tensor([ 2,  4,  6,  8, 10])

In [55]:
#tensor data type
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float16_tensor.dtype

torch.float32

In [66]:
#data type coersion and check shape
int32_tensor = torch.tensor([3, 4, 5], dtype=torch.long)
print(int32_tensor.size())
print(int32_tensor.shape)

torch.Size([3])
torch.Size([3])


In [65]:
multiplied_tensor = float16_tensor * int32_tensor
print(multiplied_tensor)
print(multiplied_tensor.dtype)
print(multiplied_tensor.device)

tensor([ 9., 24., 45.])
torch.float32
cpu


In [71]:
int32_tensor_2 = torch.tensor([5,6,7])
int32_tensor_3 = torch.tensor([1,2,3])
division_tensor = int32_tensor_2 / int32_tensor_3
print(division_tensor)
print(division_tensor.dtype)

tensor([5.0000, 3.0000, 2.3333])
torch.float32


In [64]:
#tensor type conversion
old_tensor = torch.tensor([1.1, 2.2, 3.3], dtype=torch.float32)
print(old_tensor.dtype)
new_tensor = old_tensor.type(torch.float16)
print(new_tensor.dtype)
print(new_tensor)

torch.float32
torch.float16
tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16)


In [76]:
#tensor manipulation (built-in): vector-scalar multiplication
print(new_tensor)
#use * in python unless specified for simplification
print(new_tensor*10)
print(torch.mul(new_tensor, 10))

tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16)
tensor([11., 22., 33.], dtype=torch.float16)
tensor([11., 22., 33.], dtype=torch.float16)


In [ ]:
#matrix multiplcation: dot product
