In [1]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

2.0.0
We have a GPU!


In [9]:
#check GPU details

!nvidia-smi

Sun Jun  4 00:28:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.92       Driver Version: 528.92       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0    20W /  65W |      0MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [11]:
#device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)
print("Device count:", torch.cuda.device_count())

Device: cuda
Device count: 1


In [23]:
#place tensors in GPU for faster computations

tensor_for_gpu = torch.rand(3, 3) #in CPU
print(tensor_for_gpu, tensor_for_gpu.device)
tensor_for_gpu = tensor_for_gpu.to(device)
print(tensor_for_gpu, tensor_for_gpu.device)

tensor([[0.6004, 0.0484, 0.0350],
        [0.3234, 0.0209, 0.4409],
        [0.1065, 0.9826, 0.4041]]) cpu
tensor([[0.6004, 0.0484, 0.0350],
        [0.3234, 0.0209, 0.4409],
        [0.1065, 0.9826, 0.4041]], device='cuda:0') cuda:0


In [24]:
#place tensors from GPU back to CPU, eg. to use NumPy

tensor_for_cpu = tensor_for_gpu.cpu()
print(tensor_for_cpu, tensor_for_cpu.device)
print(tensor_for_gpu, tensor_for_gpu.device)

tensor([[0.6004, 0.0484, 0.0350],
        [0.3234, 0.0209, 0.4409],
        [0.1065, 0.9826, 0.4041]]) cpu
tensor([[0.6004, 0.0484, 0.0350],
        [0.3234, 0.0209, 0.4409],
        [0.1065, 0.9826, 0.4041]], device='cuda:0') cuda:0
