In [19]:
import torch
import numpy as np

device = "cuda" if torch.cuda.is_available else "cpu"

In [5]:
random_tensor_1 = torch.rand(7, 7)
print(random_tensor_1)
random_tensor_2 = torch.rand(1, 7)
print(random_tensor_2)
result_1 = torch.matmul(random_tensor_1, random_tensor_2.T)
print(result_1)

tensor([[0.6015, 0.0349, 0.1166, 0.9074, 0.7016, 0.4744, 0.5582],
        [0.3284, 0.8346, 0.4440, 0.6786, 0.3734, 0.0300, 0.3552],
        [0.3333, 0.8930, 0.3600, 0.3409, 0.5996, 0.7914, 0.5517],
        [0.9433, 0.9013, 0.6441, 0.6658, 0.3970, 0.9556, 0.9630],
        [0.6693, 0.5345, 0.4486, 0.4933, 0.7767, 0.2862, 0.4932],
        [0.1647, 0.3311, 0.7793, 0.5160, 0.1238, 0.9936, 0.3269],
        [0.7933, 0.4054, 0.4328, 0.9846, 0.7933, 0.8819, 0.2929]])
tensor([[0.8195, 0.0643, 0.8674, 0.6878, 0.1482, 0.0157, 0.1761]])
tensor([[1.4302],
        [1.2930],
        [1.0758],
        [2.0911],
        [1.5178],
        [1.2786],
        [1.9119]])


In [16]:
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)

In [22]:
torch.manual_seed(1234)
random_tensor_1 = torch.rand(2, 3).to(device)
print(random_tensor_1)
torch.manual_seed(1234)
random_tensor_2 = torch.rand(2, 3).to(device)
print(random_tensor_2)
torch.matmul(random_tensor_1, random_tensor_2.T)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [28]:
torch.manual_seed(0)
random_tensor_1 = torch.rand(2, 3).to(device)
print(random_tensor_1)
print(torch.manual_seed(0))
random_tensor_2 = torch.rand(2, 3).to(device)
print(random_tensor_2)
result_3 = torch.matmul(random_tensor_1, random_tensor_2.T)
print(result_3)
print(result_3.max(), result_3.min())
print(result_3.argmax(), result_3.argmin())

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]], device='cuda:0')
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]], device='cuda:0')
tensor([[0.8443, 0.3578],
        [0.3578, 0.5140]], device='cuda:0')
tensor(0.8443, device='cuda:0') tensor(0.3578, device='cuda:0')
tensor(0, device='cuda:0') tensor(1, device='cuda:0')


In [49]:
torch.manual_seed(7)
random_tensor_3 = torch.rand(1, 1, 1, 10)
print(random_tensor_3)
random_tensor_3 = random_tensor_3.squeeze().squeeze()
print(random_tensor_3.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([10])
